# Generated by Django 5.2.7 on 2025-11-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='Apellidos',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='email',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='Nombre',
        ),
    ]
