# Generated by Django 5.2.7 on 2025-11-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_rename_last_name_customuser_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Estatus', models.BooleanField(default=True)),
                ('Cta', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HolderUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('fhRegistro', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
